### ISSUE TITLE
Can you implement the iOS authentication as well?

### ISSUE THREAD

**Issue by IdanLevi** [neaorin/AzureMobileAppsDemo-XamarinForms#1]

**Comment by neaorin** [comment]
Hi, I don't actually have a Mac to test on right now, but looking at [the documentation for App Service iOS auth](https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-get-started-users/#add-authentication-to-the-ios-app), the way to implement server-side authentication flow for iOS would be:
1. Make the `sorindemo.iOS.AppDelegate` class implement the `sorindemo.IAuthenticate` interface:
   
    `public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate, IAuthenticate`
2. In this class implement the `Authenticate` method like this:
   
   `
   public async Task<MobileServiceUser> Authenticate(MobileServiceAuthenticationProvider provider)
       {
           var user = await TodoItemManager.DefaultManager.CurrentClient.LoginAsync(UIApplication.SharedApplication.KeyWindow.RootViewController, provider);
           return user;
       }
   `
3. In `sorindemo.iOS.AppDelegate.FinishedLaunching()` add the following line before `LoadApplication`:
   
   `App.Init(this);`

**Comment by IdanLevi** [comment]
Thanks for your answer.

I did exactly like that on my app but the call "LoginAsync" gets stuck and never returns on iOS :(

**Comment by neaorin** [comment]
I committed a version which for me has all the supported authentication providers working on the iOS simulator (iOS 9.3, http://macincloud.com/ to the rescue!).

Is it working for you? 
Perhaps you have something misconfigured on the Azure side?

**Comment by IdanLevi** [comment]
Yeah it was my bad..The problem is App.Init(this) was not in the right order in AppDelegate. :(
(Due to a migration to a different UI that initializes things a bit different)
That fixed it, thanks a lot!
